networks:
   todo_network:
     external: false

services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - todo_network

  api:
    build: .
    depends_on:
      - db
    networks:
      - todo_network
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
    ports:
      - 3000:3000


volumes:
  postgres_data:
